version: "3.5"

services:
    database:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - 'mysql_data:/var/lib/mysql'
        environment:
            APP_ENV: dev
            MYSQL_DATABASE: symfony-rest-api-init
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306

    nginx:
        image: nginx:1.16-alpine
        ports:
            - '8080:80'
        volumes:
            - './public:/var/www/api/public:ro'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

    php:
        image: symfony-rest-api-init-php_fpm
        working_dir: /var/www/api
        depends_on:
            - database
        environment:
            APP_ENV: dev
            ENABLED_EXCEPTION_DEV: 1
            PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
            XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1 remote_host=127.0.0.1 idekey=PHPSTORM"
            PHP_IDE_CONFIG: "serverName=debugServer"
        volumes:
            - .:/var/www/api
            - ./docker/fpm/pool.d/application.conf:/opt/docker/etc/php/fpm/pool.d/application.conf
            - ./docker/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./var:/var/www/api/var

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        ports:
            - '8082:80'
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: database

volumes:
    mysql_data:
        driver: local

networks:
    default:
        name: app-network
